### ISSUE TITLE
Work around iiasa/ixmp#425

### ISSUE THREAD

**Issue by khaeru** [iiasa/message-ix-models#45]
@Jihoon reports that when calling `apply_spec()` with a spec that adds unit `""` (dimensionless), one runs into iiasa/ixmp#425 (i.e. only when connecting via ixmp JDBCBackend to a Oracle remote database). 

For example, this is triggered by `message_data.model.transport` via entries in its set.yaml config file:
https://github.com/iiasa/message_data/blob/5f572d2a50f69aa90663d2c1aa97d4895ef32b94/data/transport/set.yaml#L130-L135
```yaml
unit:
  add:
    "": dimensionless
    km: kilometre
    ...
```

Since the ixmp bug is in the Java code, it is unlikely to get fixed, and message-ix-models must work around it. The workaround will be for `apply_spec()` to detect when a unit is `""` and skip adding it.

**Comment by khaeru** [comment]
@Jihoon also notes that the workaround could be done in the ixmp Python code itself.

**Comment by Jihoon** [comment]
I find there is another trigger from `message_ix_models.model.disutility`. 
https://github.com/iiasa/message-ix-models/blob/490fa9cbd3a46bc84a4ca91f4eb777b635de300c/message_ix_models/model/disutility.py#L68

**Comment by khaeru** [comment]
Reopening as @volker-krey indicates the fix does not work as intended. A traceback is below.
https://github.com/iiasa/message-ix-models/blob/fbf406c6e84ff23dd4206d979350547ff1923e96/message_ix_models/model/build.py#L23-L26
… `str(e)` is probably leading to something like `at.ac.iiasa.ixmp.exceptions.at.ac.iiasa.ixmp.exceptions.IxException: at.ac.iiasa.ixmp.exceptions.IxException: Error assigning an unit-key-id mapping in the database!`, so some part of this string should be checked. The Java code obscures the OracleDatabaseException class.

It is not possible to write tests for this code/workaround, because we do not have a way of starting a temporary Oracle database server on test runners.

```
Traceback (most recent call last):
  File "Platform.java", line 678, in at.ac.iiasa.ixmp.Platform.addUnitToDB
  File "DbDAO.java", line 1332, in at.ac.iiasa.ixmp.database.DbDAO.addUnitToDB
  File "HikariProxyPreparedStatement.java", line -1, in com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeUpdate
  File "ProxyPreparedStatement.java", line 61, in com.zaxxer.hikari.pool.ProxyPreparedStatement.executeUpdate
  File "OraclePreparedStatementWrapper.java", line 1061, in oracle.jdbc.driver.OraclePreparedStatementWrapper.executeUpdate
  File "OraclePreparedStatement.java", line 3710, in oracle.jdbc.driver.OraclePreparedStatement.executeUpdate
  File "OraclePreparedStatement.java", line 3730, in oracle.jdbc.driver.OraclePreparedStatement.executeLargeUpdate
  File "T4CPreparedStatement.java", line 1384, in oracle.jdbc.driver.T4CPreparedStatement.executeInternal
  File "OraclePreparedStatement.java", line 3640, in oracle.jdbc.driver.OraclePreparedStatement.executeInternal
  File "OracleStatement.java", line 1136, in oracle.jdbc.driver.OracleStatement.doExecuteWithTimeout
  File "T4CPreparedStatement.java", line 928, in oracle.jdbc.driver.T4CPreparedStatement.executeForRows
  File "T4CPreparedStatement.java", line 86, in oracle.jdbc.driver.T4CPreparedStatement.doOall8
  File "T4CPreparedStatement.java", line 253, in oracle.jdbc.driver.T4CPreparedStatement.doOall8
  File "T4C8Oall.java", line 610, in oracle.jdbc.driver.T4C8Oall.doOALL
  File "T4CTTIfun.java", line 255, in oracle.jdbc.driver.T4CTTIfun.doRPC
  File "T4CTTIfun.java", line 537, in oracle.jdbc.driver.T4CTTIfun.receive
  File "T4C8Oall.java", line 1052, in oracle.jdbc.driver.T4C8Oall.processError
  File "T4CTTIoer11.java", line 446, in oracle.jdbc.driver.T4CTTIoer11.processError
  File "T4CTTIoer11.java", line 498, in oracle.jdbc.driver.T4CTTIoer11.processError
oracle.jdbc.oracle.jdbc.OracleDatabaseException: Error : 1400, Position : 72, Sql = INSERT INTO ix_unit (id,name, cre_user, cre_date, scheme) VALUES (:1 , :2 , :3 , CURRENT_TIMESTAMP, :4 ), OriginalSql = INSERT INTO ix_unit (id,name, cre_user, cre_date, scheme) VALUES (?, ?, ?, CURRENT_TIMESTAMP, ?), Error Msg = ORA-01400: cannot insert NULL into ("IXMP_DEV"."IX_UNIT"."NAME")


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "Platform.java", line 678, in at.ac.iiasa.ixmp.Platform.addUnitToDB
  File "DbDAO.java", line 1332, in at.ac.iiasa.ixmp.database.DbDAO.addUnitToDB
  File "HikariProxyPreparedStatement.java", line -1, in com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeUpdate
  File "ProxyPreparedStatement.java", line 61, in com.zaxxer.hikari.pool.ProxyPreparedStatement.executeUpdate
  File "OraclePreparedStatementWrapper.java", line 1061, in oracle.jdbc.driver.OraclePreparedStatementWrapper.executeUpdate
  File "OraclePreparedStatement.java", line 3710, in oracle.jdbc.driver.OraclePreparedStatement.executeUpdate
  File "OraclePreparedStatement.java", line 3730, in oracle.jdbc.driver.OraclePreparedStatement.executeLargeUpdate
  File "T4CPreparedStatement.java", line 1384, in oracle.jdbc.driver.T4CPreparedStatement.executeInternal
  File "OraclePreparedStatement.java", line 3640, in oracle.jdbc.driver.OraclePreparedStatement.executeInternal
  File "OracleStatement.java", line 1136, in oracle.jdbc.driver.OracleStatement.doExecuteWithTimeout
  File "T4CPreparedStatement.java", line 928, in oracle.jdbc.driver.T4CPreparedStatement.executeForRows
  File "T4CPreparedStatement.java", line 86, in oracle.jdbc.driver.T4CPreparedStatement.doOall8
  File "T4CPreparedStatement.java", line 253, in oracle.jdbc.driver.T4CPreparedStatement.doOall8
  File "T4C8Oall.java", line 610, in oracle.jdbc.driver.T4C8Oall.doOALL
  File "T4CTTIfun.java", line 255, in oracle.jdbc.driver.T4CTTIfun.doRPC
  File "T4CTTIfun.java", line 537, in oracle.jdbc.driver.T4CTTIfun.receive
  File "T4C8Oall.java", line 1052, in oracle.jdbc.driver.T4C8Oall.processError
  File "T4CTTIoer11.java", line 446, in oracle.jdbc.driver.T4CTTIoer11.processError
  File "T4CTTIoer11.java", line 494, in oracle.jdbc.driver.T4CTTIoer11.processError
java.sql.java.sql.SQLIntegrityConstraintViolationException: java.sql.SQLIntegrityConstraintViolationException: ORA-01400: cannot insert NULL into ("IXMP_DEV"."IX_UNIT"."NAME")


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "Platform.java", line 678, in at.ac.iiasa.ixmp.Platform.addUnitToDB
  File "DbDAO.java", line 1336, in at.ac.iiasa.ixmp.database.DbDAO.addUnitToDB
  File "DbDAO.java", line 1088, in at.ac.iiasa.ixmp.database.DbDAO.loggedIxException
Exception: Java Exception

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\krey\anaconda3\envs\message_env\Scripts\mix-models-script.py", line 33, in <module>
    sys.exit(load_entry_point('message-ix-models', 'console_scripts', 'mix-models')())
  File "C:\Users\krey\anaconda3\envs\message_env\lib\site-packages\click\core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\krey\anaconda3\envs\message_env\lib\site-packages\click\core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "C:\Users\krey\anaconda3\envs\message_env\lib\site-packages\click\core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\krey\anaconda3\envs\message_env\lib\site-packages\click\core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\krey\anaconda3\envs\message_env\lib\site-packages\click\core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\krey\anaconda3\envs\message_env\lib\site-packages\click\core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "C:\Users\krey\anaconda3\envs\message_env\lib\site-packages\click\decorators.py", line 38, in new_func
    return f(get_current_context().obj, *args, **kwargs)
  File "c:\users\krey\documents\git\message_data\message_data\model\transport\cli.py", line 122, in build_cmd
    build.main(context, scenario, **options)
  File "c:\users\krey\documents\git\message_data\message_data\model\transport\build.py", line 120, in main
    build.apply_spec(scenario, spec, partial(add_data, context=context), **options)
  File "c:\users\krey\documents\git\message-ix-models\message_ix_models\model\build.py", line 142, in apply_spec
    _add_unit(scenario.platform, unit.id, str(unit.name))
  File "c:\users\krey\documents\git\message-ix-models\message_ix_models\model\build.py", line 21, in _add_unit
    mp.add_unit(unit, comment)
  File "C:\Users\krey\anaconda3\envs\message_env\lib\site-packages\ixmp\core\platform.py", line 259, in add_unit
    self._backend.set_unit(unit, comment)
  File "C:\Users\krey\anaconda3\envs\message_env\lib\site-packages\ixmp\backend\jdbc.py", line 462, in set_unit
    self.jobj.addUnitToDB(name, comment)
at.ac.iiasa.ixmp.exceptions.at.ac.iiasa.ixmp.exceptions.IxException: at.ac.iiasa.ixmp.exceptions.IxException: Error assigning an unit-key-id mapping in the database!
```

**Comment by khaeru** [comment]
> I find there is another trigger from `message_ix_models.model.disutility`.
> 
> https://github.com/iiasa/message-ix-models/blob/490fa9cbd3a46bc84a4ca91f4eb777b635de300c/message_ix_models/model/disutility.py#L68

Per discussion with @volker-krey, the issue here is not only the adding of the unit, but also that the existing `message_ix_models.model.disutility` code creates parameter values (e.g. for `input`, `output`) which are dimensionless. Because the ixmp bug prevents dimensionless unit ("") being added to the Platform, these parameter values also cannot be added to Scenarios on the Platform.

The code is theoretically correct, in the sense that (dis)utility in economics is dimensionless, but it looks like we will have to step away from this and introduce non-dimensionless units in order to work around the bug. I will open a PR.
